### ISSUE TITLE
Tkinter canvas breakage during video streaming with UI

### ISSUE THREAD

**Issue by chpk** [niknarra/SE-Project---IntelliMeet#4]
Getting "[AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'](https://stackoverflow.com/questions/50662773/attributeerror-photoimage-object-has-no-attribute-photoimage-photo)" error while streaming videos with UI @siva-sagar @krishna-creator 
![Screenshot 2023-04-24 035031](https://user-images.githubusercontent.com/29367104/233933060-67545563-aecc-4ce4-8332-8c78e8f380a8.png)

**Comment by siva-sagar** [comment]
Added try catch method in the Tkinter UI to handle this edge case ( where null image is received from the other end)
